lib/ferry_web/router.ex
defmodule FerryWeb.Router do
  use FerryWeb, :router
  import Redirect

  import FerryWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :setup_auth do
    plug Ferry.Auth.SetupPipeline
    plug :assign_current_group
  end

  pipeline :ensure_auth do
    plug Ferry.Auth.EnsurePipeline
  end

  pipeline :authorization do
    plug Ferry.Auth.AuthorizePipeline
  end

  pipeline :chat do
    plug :assign_chat_meta
  end

  pipeline :api do
    plug Plug.Parsers,
      parsers: [:urlencoded, :multipart, :json, Absinthe.Plug.Parser],
      pass: ["*/*"],
      json_decoder: Jason
  end

  scope "/" do
    pipe_through :browser

    forward "/health", HeartCheck.Plug, heartcheck: FerryWeb.HeartCheck
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    get "/", HomePageController, :index
  end

  scope "/public", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    resources "/signup", UserController, only: [:new, :create], singleton: true
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    resources "/groups", GroupController, only: [:index, :show] do
      # TODO: move into admin scope
      resources "/users", UserController, only: [:new, :create]
    end

    resources "/inventory", InventoryListController, only: [:show], singleton: true
    resources "/map", MapController, only: [:show], singleton: true
    resources "/shipments", ShipmentOverviewController, only: [:index, :show]
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :ensure_auth, :authorization, :chat]

    resources "/groups", GroupController, only: [:edit, :update, :delete] do
      resources "/addresses", AddressController, except: [:index, :show]
      resources "/links", LinkController, except: [:show]
      resources "/projects", ProjectController, except: [:index, :show]
      resources "/inventory", StockController, except: [:show]
      resources "/users", UserController, only: [:edit, :update]

      resources "/shipments", ShipmentController do
        resources "/roles", RoleController, except: [:index, :show]
        resources "/routes", RouteController, except: [:index, :show]
      end
    end
  end

  # TODO: move "/public/groups/:group_id/users" to admin scope
  scope "/admin", FerryWeb do
    # TODO: restrict access to admin scope
    pipe_through [:browser, :setup_auth]

    # categories are visible / accessible via AidItemController:index
    resources "/aid/categories", AidCategoryController, except: [:index, :show]
    resources "/aid/items", AidItemController, except: [:show]
    resources "/aid/mods", AidModController, except: [:show]
  end

  redirect "/admin", "/admin/aid/items", :temporary
  redirect "/admin/aid", "/admin/aid/items", :temporary

  scope "/.well-known", FerryWeb do
    get "/jwks.json", JWKSController, :show, singleton: true
  end

  scope "/api" do
    pipe_through [:api]

    forward "/graphiql",
            Absinthe.Plug.GraphiQL,
            schema: FerryApi.Schema

    forward "/",
            Absinthe.Plug,
            schema: FerryApi.Schema
  end
end

lib/ferry_web/controllers/home_page_controller.ex
defmodule FerryWeb.HomePageController do
  use FerryWeb, :controller


  # Home Page Controller
  # ================================================================================

  # Show
  # ------------------------------------------------------------

  def index(%{assigns: assigns} = conn, _params) do
    case assigns[:current_group] do
      nil -> render conn, "index-public.html"
      group -> render conn, "index-group.html", group: group
    end
  end
end

lib/ferry_web/views/home_page_view.ex
defmodule FerryWeb.HomePageView do
  use FerryWeb, :view
end

lib/ferry_web/templates/home_page/index-group.html.eex
<div class="flex-centered">
  <section class="section section--multi col-9">

    <header class="section__content">
      <div class="content-header content-header--no-underline">
        <%= component "group_logo.partial.html", %{
          conn: @conn,
          group: @group,
          size: :xxl
        } %>

        <h1 class="content-header__title"><%= @group.name %></h1>
      </div>
    </header>

    <div class="section__content">
      <div class="content-header content-header--no-underline">
        <div class="content-header__title">
          <h2>About the Beta</h2>
        </div>
      </div>

      <p>
        Welcome to the Distribute Aid platform, and thank you so much for
        joining our beta test!  Please get in touch if you have an idea for
        a great new feature, notice anything we can improve on, or want to
        refer a friend:
      </p>

      <ul>
        <li>
          Email our team at: <a href="mailto:help@distributeaid.org" target="blank">help@distributeaid.org</a>
        </li>
        <li>
          <a href="https://www.facebook.com/DistributeAidDotOrg/" target="blank">Send us a message on Facebook</a>
        </li>
        <li>
          Contact Taylor (our tech lead) on WhatsApp: +44 7445 823932
        </li>
      </ul>
    </div>

  </section>
</div>

<!--
<section class="section section--wider">
  <div class="section__content">
    <header class="section__header">
      <%= component "group_logo.partial.html", %{
        conn: @conn,
        group: @group,
        size: :xxl
      } %>
      <h1 class="section__title">
        <%= @group.name %>
      </h1>
    </header>

    <div class="subsection p-centered col-9">
      <h2 class="subsection__header">Your Tools</h2>

      <p>
        You can access the public tools through the main navbar.  The following
        links will take you to your group-specific tools, where you can update
        your information or collaborate privately with other groups.
      </p>

      <div class="category">
        <%= link to: Routes.group_path(@conn, :show, @group), class: "link--wrapper" do %>
          <%= component "category-entry.partial.html", %{
            title: "Group Profile",
            icon: %{class: "fas fa-3x fa-users"}
          } %>
        <% end %>

        <%= link to: Routes.group_stock_path(@conn, :index, @group), class: "link--wrapper" do %>
          <%= component "category-entry.partial.html", %{
            title: "Inventory Manager",
            icon: %{class: "fas fa-3x fa-boxes"}
          } %>
        <% end %>

        <%= link to: Routes.group_shipment_path(@conn, :index, @group), class: "link--wrapper" do %>
          <%= component "category-entry.partial.html", %{
            title: "Shipment Coordinator",
            icon: %{class: "fas fa-3x fa-truck"}
          } %>
        <% end %>
      </div>

    </div>

    <div class="subsection p-centered col-9">
      <h2 class="subsection__header">About the Beta</h2>

      <p>
        Welcome to the Distribute Aid platform, and thank you so much for
        joining our beta test!  Please get in touch if you have an idea for
        a great new feature, notice anything we can improve on, or want to
        refer a friend:
      </p>

      <ul>
        <li>
          Email our team at: <a href="mailto:help@distributeaid.org" target="blank">help@distributeaid.org</a>
        </li>
        <li>
          <a href="https://www.facebook.com/DistributeAidDotOrg/" target="blank">Send us a message on Facebook</a>
        </li>
        <li>
          Contact Taylor (our tech lead) on WhatsApp: +44 7445 823932
        </li>
      </ul>
    </div>

  </div>
</section>
-->

lib/ferry_web/templates/home_page/index-public.html.eex
<div class="flex-centered">
  <section class="section section--text col-9">

    <header class="section__header">
      <h1>Welcome!</h1>
    </header>

    <div class="section__content">
      <p>
        After a year of work, Distribute Aid is now in Beta!  Feel free to check
        out our public tools, and be sure to stay in touch:
      </p>

      <ul>
        <li>
          Email our team at <a href="mailto:help@distributeaid.org" target="blank">hello@distributeaid.org</a> to introduce your aid group and schedule a demo.
        </li>
        <li>
          <a href="https://www.facebook.com/DistributeAidDotOrg/" target="blank">Follow us on Facebook</a> for the latest updates.
        </li>
      </ul>
    </div>

    <footer class="section__footer">
      <%= link to: Routes.session_path(@conn, :new), class: "btn btn-lg btn-primary" do %>
        <i class="fas fa-unlock is-icon-left"></i> Login
      <% end %>
      <%= link to: Routes.user_path(@conn, :new), class: "btn btn-lg btn-primary" do %>
        <i class="fas fa-plus-circle is-icon-left"></i> Signup
      <% end %>      
    </footer>

  </section>
</div>