lib/ferry_web/router.ex
defmodule FerryWeb.Router do
  use FerryWeb, :router
  import Redirect

  import FerryWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :setup_auth do
    plug Ferry.Auth.SetupPipeline
    plug :assign_current_group
  end

  pipeline :ensure_auth do
    plug Ferry.Auth.EnsurePipeline
  end

  pipeline :authorization do
    plug Ferry.Auth.AuthorizePipeline
  end

  pipeline :chat do
    plug :assign_chat_meta
  end

  pipeline :api do
    plug Plug.Parsers,
      parsers: [:urlencoded, :multipart, :json, Absinthe.Plug.Parser],
      pass: ["*/*"],
      json_decoder: Jason
  end

  scope "/" do
    pipe_through :browser

    forward "/health", HeartCheck.Plug, heartcheck: FerryWeb.HeartCheck
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    get "/", HomePageController, :index
  end

  scope "/public", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    resources "/signup", UserController, only: [:new, :create], singleton: true
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    resources "/groups", GroupController, only: [:index, :show] do
      # TODO: move into admin scope
      resources "/users", UserController, only: [:new, :create]
    end

    resources "/inventory", InventoryListController, only: [:show], singleton: true
    resources "/map", MapController, only: [:show], singleton: true
    resources "/shipments", ShipmentOverviewController, only: [:index, :show]
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :ensure_auth, :authorization, :chat]

    resources "/groups", GroupController, only: [:edit, :update, :delete] do
      resources "/addresses", AddressController, except: [:index, :show]
      resources "/links", LinkController, except: [:show]
      resources "/projects", ProjectController, except: [:index, :show]
      resources "/inventory", StockController, except: [:show]
      resources "/users", UserController, only: [:edit, :update]

      resources "/shipments", ShipmentController do
        resources "/roles", RoleController, except: [:index, :show]
        resources "/routes", RouteController, except: [:index, :show]
      end
    end
  end

  # TODO: move "/public/groups/:group_id/users" to admin scope
  scope "/admin", FerryWeb do
    # TODO: restrict access to admin scope
    pipe_through [:browser, :setup_auth]

    # categories are visible / accessible via AidItemController:index
    resources "/aid/categories", AidCategoryController, except: [:index, :show]
    resources "/aid/items", AidItemController, except: [:show]
    resources "/aid/mods", AidModController, except: [:show]
  end

  redirect "/admin", "/admin/aid/items", :temporary
  redirect "/admin/aid", "/admin/aid/items", :temporary

  scope "/.well-known", FerryWeb do
    get "/jwks.json", JWKSController, :show, singleton: true
  end

  scope "/api" do
    pipe_through [:api]

    forward "/graphiql",
            Absinthe.Plug.GraphiQL,
            schema: FerryApi.Schema

    forward "/",
            Absinthe.Plug,
            schema: FerryApi.Schema
  end
end

lib/ferry_web/views/layout_view.ex
defmodule FerryWeb.LayoutView do
  use FerryWeb, :view

  def chat_meta(nil) do
    ""
  end

  def chat_meta(meta) do
    chatCfg = Application.get_env(:ferry, :chat)
    apiKey = Keyword.fetch!(chatCfg, :apiKey)
    endpoint = Keyword.fetch!(chatCfg, :endpoint)
    ~E(
      <!-- Chat -->
      <meta name="chat:jwt" content="<%= meta.token %>">
      <meta name="chat:context" content="<%= meta.context %>">
      <meta name="chat:apiKey" content="<%= apiKey %>">
      <meta name="chat:endpoint" content="<%= endpoint %>">
    )
  end

end

lib/ferry_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Distribute Aid</title>

    <!--
    Styles
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Quicksand:400,700&display=swap" rel="stylesheet">
    <link href="<%= Routes.static_path(@conn, "/css/vendors~app.css") %>" rel="stylesheet">
    <link href="<%= Routes.static_path(@conn, "/css/app.css") %>" rel="stylesheet">
    <%= render_existing @view_module, "view-specific-styles.html" %>

    <!--
    Favicon
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    -->
    <link rel="apple-touch-icon" sizes="57x57" href="<%= Routes.static_path(@conn, "/apple-icon-57x57.png") %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= Routes.static_path(@conn, "/apple-icon-60x60.png") %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= Routes.static_path(@conn, "/apple-icon-72x72.png") %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= Routes.static_path(@conn, "/apple-icon-76x76.png") %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= Routes.static_path(@conn, "/apple-icon-114x114.png") %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= Routes.static_path(@conn, "/apple-icon-120x120.png") %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= Routes.static_path(@conn, "/apple-icon-144x144.png") %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= Routes.static_path(@conn, "/apple-icon-152x152.png") %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/apple-icon-180x180.png") %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= Routes.static_path(@conn, "/android-icon-192x192.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= Routes.static_path(@conn, "/favicon-96x96.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/favicon-16x16.png") %>">
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/manifest.json") %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= Routes.static_path(@conn, "/ms-icon-144x144.png") %>">
    <meta name="theme-color" content="#ffffff">

    <%= chat_meta(assigns[:chat_meta]) %>

    <!--
    Scripts
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    -->
    <script defer src="<%= Routes.static_path(@conn, "/js/vendors~app.js") %>"></script>
    <script defer src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing @view_module, "view-specific-scripts.html" %>
    <script>
      if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register("/stillsuit.js")
          .then(function(registration) {
            console.log('ServiceWorker registration successful with scope: ', registration.scope);
          })
          .catch(function(err) {
            console.log('ServiceWorker registration failed: ', err);
          });
      }
    </script>
  </head>

  <body class="site columns col-gapless">

    <header class="site-header column col-auto">
      <%= img_tag Routes.static_path(@conn, "/images/logos/DA_lettermark_blue.svg"), class: "site-header__logo", alt: "Distribute Aid Logo: Outline of Doves" %>

      <hr class="site-header__divider" />

      <nav>
        <ul class="site-nav">
          <%= img_tag Routes.static_path(@conn, "/images/logos/DA_lettermark_blue.svg"), class: "site-header__logo -mobile", alt: "Distribute Aid Logo: Outline of Doves" %>
          <div role="presentation" class="site-nav__top">
            <li class="col-md-auto">
              <%= link to: Routes.home_page_path(@conn, :index) do %>
                <i class="fas fa-fw fa-home"></i> Dashboard
              <% end %>
            </li>
            <li class="col-md-auto">
              <%= if @current_user == nil do %>
                <%= link to: Routes.session_path(@conn, :new) do %>
                  <i class="fas fa-fw fa-unlock-alt"></i> Login / Signup
                <% end %>
              <% else %>
                <%= link to: Routes.session_path(@conn, :delete), method: :delete do %>
                  <i class="fas fa-fw fa-lock"></i> Logout
                <% end %>
              <% end %>
            </li>
          </div>
          <li>
            <hr class="site-header__divider" />
          </li>
          <div role="presentation" class="site-nav__bottom">
            <li>
              <%= link to: Routes.group_path(@conn, :index) do %>
                <i class="fas fa-fw fa-user-circle"></i> Aid Groups
              <% end %>
            </li>
            <li>
              <%= link to: Routes.map_path(@conn, :show) do %>
                <i class="fas fa-fw fa-map-marker-alt"></i> Map
              <% end %>
            </li>
            <li>
              <%= link to: Routes.inventory_list_path(@conn, :show) do %>
                <i class="fas fa-fw fa-boxes"></i> Inventory
              <% end %>
            </li>
            <li>
              <%= link to: Routes.shipment_overview_path(@conn, :index) do %>
                <i class="fas fa-fw fa-truck"></i> Shipments
              <% end %>
            </li>
          </div>
        </ul>
      </nav>

      <hr class="site-header__divider" />

      <ul class="site-nav site-nav--small">
        <li>
          <%= if @current_user do %>
            <%= link to: Routes.group_user_path(@conn, :edit, @current_user.group_id, @current_user) do %>
              <i class="fas fa-fw fa-lock"></i> Change Password
            <% end %>
          <% end %>
        </li>

        <li>
          <%= if @current_user do %>
            <a href="mailto:help@distributeaid.org">
              <i class="fas fa-fw fa-paper-plane"></i> help@distributeaid.org
            </a>
          <% else %>
            <a href="mailto:hello@distributeaid.org">
              <i class="fas fa-fw fa-paper-plane"></i> hello@distributeaid.org
            </a>
          <% end %>
        </li>
        <li>
          <a href="https://gitlab.com/users/distribute-aid/projects" target="_blank">
            <i class="fas fa-fw fa-code"></i> Code
          </a>
        </li>
        <li>
          <a href="https://www.patreon.com/distributeaid" target="_blank">
            <i class="fas fa-fw fa-euro-sign"></i> Support Us
          </a>
        </li>
      </ul>
    </header>

    <main class="site-content column" role="main">
      <!--
      <div class="flash">
        <%= if message = get_flash(@conn, :success) do %>
          <p class="toast toast-success" role="alert"><%= message %></p>
        <% end %>

        <%= if message = get_flash(@conn, :info) do %>
          <p class="toast" role="alert"><%= message %></p>
        <% end %>

        <%= if message = get_flash(@conn, :error) do %>
          <p class="toast toast-error" role="alert"><%= message %></p>
        <% end %>
      </div>
      -->

      <%= render @view_module, @view_template, assigns %>
    </main>

    <ul class="site-nav site-nav--mobile">
      <li>
        <%= if @current_user do %>
          <%= link to: Routes.group_user_path(@conn, :edit, @current_user.group_id, @current_user) do %>
            <i class="fas fa-fw fa-lock"></i> Change Password
          <% end %>
        <% end %>
      </li>

      <li>
        <%= if @current_user do %>
          <a href="mailto:help@distributeaid.org">
            <i class="fas fa-fw fa-paper-plane"></i> help@distributeaid.org
          </a>
        <% else %>
          <a href="mailto:hello@distributeaid.org">
            <i class="fas fa-fw fa-paper-plane"></i> hello@distributeaid.org
          </a>
        <% end %>
      </li>
      <li>
        <a href="https://gitlab.com/users/distribute-aid/projects" target="_blank">
          <i class="fas fa-fw fa-code"></i> Code
        </a>
      </li>
      <li>
        <a href="https://www.patreon.com/distributeaid" target="_blank">
          <i class="fas fa-fw fa-euro-sign"></i> Support Us
        </a>
      </li>
    </ul>

    <!-- Chat -->
    <script src="https://cdn.rawgit.com/muicss/loadjs/4.2.0/dist/loadjs.min.js" async></script>
    <script src="<%= Routes.static_path(@conn, "/js/chat.js") %>" async></script>
  </body>
</html>