lib/ferry_web/router.ex
defmodule FerryWeb.Router do
  use FerryWeb, :router
  import Redirect

  import FerryWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :setup_auth do
    plug Ferry.Auth.SetupPipeline
    plug :assign_current_group
  end

  pipeline :ensure_auth do
    plug Ferry.Auth.EnsurePipeline
  end

  pipeline :authorization do
    plug Ferry.Auth.AuthorizePipeline
  end

  pipeline :chat do
    plug :assign_chat_meta
  end

  pipeline :api do
    plug Plug.Parsers,
      parsers: [:urlencoded, :multipart, :json, Absinthe.Plug.Parser],
      pass: ["*/*"],
      json_decoder: Jason
  end

  scope "/" do
    pipe_through :browser

    forward "/health", HeartCheck.Plug, heartcheck: FerryWeb.HeartCheck
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    get "/", HomePageController, :index
  end

  scope "/public", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    resources "/signup", UserController, only: [:new, :create], singleton: true
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    resources "/groups", GroupController, only: [:index, :show] do
      # TODO: move into admin scope
      resources "/users", UserController, only: [:new, :create]
    end

    resources "/inventory", InventoryListController, only: [:show], singleton: true
    resources "/map", MapController, only: [:show], singleton: true
    resources "/shipments", ShipmentOverviewController, only: [:index, :show]
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :ensure_auth, :authorization, :chat]

    resources "/groups", GroupController, only: [:edit, :update, :delete] do
      resources "/addresses", AddressController, except: [:index, :show]
      resources "/links", LinkController, except: [:show]
      resources "/projects", ProjectController, except: [:index, :show]
      resources "/inventory", StockController, except: [:show]
      resources "/users", UserController, only: [:edit, :update]

      resources "/shipments", ShipmentController do
        resources "/roles", RoleController, except: [:index, :show]
        resources "/routes", RouteController, except: [:index, :show]
      end
    end
  end

  # TODO: move "/public/groups/:group_id/users" to admin scope
  scope "/admin", FerryWeb do
    # TODO: restrict access to admin scope
    pipe_through [:browser, :setup_auth]

    # categories are visible / accessible via AidItemController:index
    resources "/aid/categories", AidCategoryController, except: [:index, :show]
    resources "/aid/items", AidItemController, except: [:show]
    resources "/aid/mods", AidModController, except: [:show]
  end

  redirect "/admin", "/admin/aid/items", :temporary
  redirect "/admin/aid", "/admin/aid/items", :temporary

  scope "/.well-known", FerryWeb do
    get "/jwks.json", JWKSController, :show, singleton: true
  end

  scope "/api" do
    pipe_through [:api]

    forward "/graphiql",
            Absinthe.Plug.GraphiQL,
            schema: FerryApi.Schema

    forward "/",
            Absinthe.Plug,
            schema: FerryApi.Schema
  end
end

lib/ferry_web/controllers/aid_category_controller.ex
defmodule FerryWeb.AidCategoryController do
  use FerryWeb, :controller

  alias Ferry.AidTaxonomy
  alias Ferry.AidTaxonomy.Category

  # Read
  # ------------------------------------------------------------

  def index(conn, _params) do
    categories = AidTaxonomy.list_categories(true)
    render(conn, "index.html", categories: categories)
  end

  # NOTE: show route isn't needed

  # Create
  # ------------------------------------------------------------

  def new(conn, _params) do
    changeset = AidTaxonomy.change_category(%Category{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"category" => category_params}) do
    case AidTaxonomy.create_category(category_params) do
      {:ok, _category} ->
        conn
        |> put_flash(:info, "Category created successfully.")
        |> redirect(to: Routes.aid_item_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  # Update
  # ------------------------------------------------------------

  def edit(conn, %{"id" => id}) do
    category = AidTaxonomy.get_category!(id)
    changeset = AidTaxonomy.change_category(category)
    render(conn, "edit.html", changeset: changeset)
  end

  def update(conn, %{"id" => id, "category" => category_params}) do
    category = AidTaxonomy.get_category!(id)
    case AidTaxonomy.update_category(category, category_params) do
      {:ok, _category} ->
        conn
        |> put_flash(:info, "Category updated successfully.")
        |> redirect(to: Routes.aid_item_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "edit.html", changeset: changeset)
    end
  end

  # Delete
  # ------------------------------------------------------------

  def delete(conn, %{"id" => id}) do
    category = AidTaxonomy.get_category!(id)
    case AidTaxonomy.delete_category(category) do
      {:ok, _category} ->
        conn
        |> put_flash(:info, "Category and #{length(category.items)} related item(s) deleted successfully.  No items were linked to any aid list entries.")
        |> redirect(to: Routes.aid_item_path(conn, :index))

      # TODO: disable the delete button for categories you can't delete and show why on hover
      {:error, %Ecto.Changeset{} = _changeset} ->
        conn
        |> put_flash(:error, "Categories linked to aid list entries cannot be deleted, since doing so would also destroy user-data.")
        |> redirect(to: Routes.aid_item_path(conn, :index))
    end
  end

end

lib/ferry_web/views/aid_category_view.ex
defmodule FerryWeb.AidCategoryView do
  use FerryWeb, :view
end

lib/ferry_web/templates/aid_category/edit.html.eex
<section class="section section--tabs section--multi">
  <header class="section__header">
    <h1 class="section__title">Admin - Aid</h1>

    <nav class="section__nav">
      <ul class="section__tab tab">
        <li class="tab-item active">
          <%= link "Categories & Items", to: Routes.aid_item_path(@conn, :index) %>
        </li>
        <li class="tab-item">
          <%= link "Mods", to: Routes.aid_mod_path(@conn, :index) %>
        </li>
      </ul>
    </nav>
  </header>

  <div class="section__content">
    <h2 class="col-9 col-ml-auto">Edit A Category</h2>
    <%= render "form.partial.html", Map.put(assigns, :action, Routes.aid_category_path(@conn, :update, get_id(@changeset))) %>
  </div>

</section>

lib/ferry_web/templates/aid_category/form.partial.html.eex
<%= form_for @changeset, @action, [class: "form-horizontal"], fn f -> %>
  <%= component "required.partial.html" %>

  <%= if @changeset.action do %>
    <div class="toast toast-error">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group form-group--required <%= validation_status_class(f, :name) %>">
    <%= label f, :name %>
    <%= text_input f, :name, class: "form-input", placeholder: "Clothing" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group col-9 col-ml-auto">
    <%= submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

lib/ferry_web/templates/aid_category/new.html.eex
<section class="section section--tabs section--multi">
  <header class="section__header">
    <h1 class="section__title">Admin - Aid</h1>

    <nav class="section__nav">
      <ul class="section__tab tab">
        <li class="tab-item active">
          <%= link "Categories & Items", to: Routes.aid_item_path(@conn, :index) %>
        </li>
        <li class="tab-item">
          <%= link "Mods", to: Routes.aid_mod_path(@conn, :index) %>
        </li>
      </ul>
    </nav>
  </header>

  <div class="section__content">
    <h2 class="col-9 col-ml-auto">Add A New Category</h2>
    <%= render "form.partial.html", Map.put(assigns, :action, Routes.aid_category_path(@conn, :create)) %>
  </div>

</section>