lib/ferry_web/router.ex
defmodule FerryWeb.Router do
  use FerryWeb, :router
  import Redirect

  import FerryWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :setup_auth do
    plug Ferry.Auth.SetupPipeline
    plug :assign_current_group
  end

  pipeline :ensure_auth do
    plug Ferry.Auth.EnsurePipeline
  end

  pipeline :authorization do
    plug Ferry.Auth.AuthorizePipeline
  end

  pipeline :chat do
    plug :assign_chat_meta
  end

  pipeline :api do
    plug Plug.Parsers,
      parsers: [:urlencoded, :multipart, :json, Absinthe.Plug.Parser],
      pass: ["*/*"],
      json_decoder: Jason
  end

  scope "/" do
    pipe_through :browser

    forward "/health", HeartCheck.Plug, heartcheck: FerryWeb.HeartCheck
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    get "/", HomePageController, :index
  end

  scope "/public", FerryWeb do
    pipe_through [:browser, :setup_auth, :chat]

    resources "/signup", UserController, only: [:new, :create], singleton: true
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    resources "/groups", GroupController, only: [:index, :show] do
      # TODO: move into admin scope
      resources "/users", UserController, only: [:new, :create]
    end

    resources "/inventory", InventoryListController, only: [:show], singleton: true
    resources "/map", MapController, only: [:show], singleton: true
    resources "/shipments", ShipmentOverviewController, only: [:index, :show]
  end

  scope "/", FerryWeb do
    pipe_through [:browser, :setup_auth, :ensure_auth, :authorization, :chat]

    resources "/groups", GroupController, only: [:edit, :update, :delete] do
      resources "/addresses", AddressController, except: [:index, :show]
      resources "/links", LinkController, except: [:show]
      resources "/projects", ProjectController, except: [:index, :show]
      resources "/inventory", StockController, except: [:show]
      resources "/users", UserController, only: [:edit, :update]

      resources "/shipments", ShipmentController do
        resources "/roles", RoleController, except: [:index, :show]
        resources "/routes", RouteController, except: [:index, :show]
      end
    end
  end

  # TODO: move "/public/groups/:group_id/users" to admin scope
  scope "/admin", FerryWeb do
    # TODO: restrict access to admin scope
    pipe_through [:browser, :setup_auth]

    # categories are visible / accessible via AidItemController:index
    resources "/aid/categories", AidCategoryController, except: [:index, :show]
    resources "/aid/items", AidItemController, except: [:show]
    resources "/aid/mods", AidModController, except: [:show]
  end

  redirect "/admin", "/admin/aid/items", :temporary
  redirect "/admin/aid", "/admin/aid/items", :temporary

  scope "/.well-known", FerryWeb do
    get "/jwks.json", JWKSController, :show, singleton: true
  end

  scope "/api" do
    pipe_through [:api]

    forward "/graphiql",
            Absinthe.Plug.GraphiQL,
            schema: FerryApi.Schema

    forward "/",
            Absinthe.Plug,
            schema: FerryApi.Schema
  end
end

lib/ferry/profiles/group.ex
defmodule Ferry.Profiles.Group do
  use Ecto.Schema
  use Arc.Ecto.Schema
  import Ecto.Changeset

  alias Ferry.Accounts.User
  alias Ferry.Profiles.Group.Logo
  alias Ferry.Profiles.Project


  schema "groups" do
    field :name, :string
    field :description, :string
    field :logo, Logo.Type

    has_one :users, User # on_delete set in database via migration
    has_many :projects, Project # on_delete set in database via migration

    timestamps()
  end

  @doc false
  def changeset(group, attrs) do
    group
    |> cast(attrs, [:name, :description])
    |> validate_required([:name])
    |> validate_length(:name, min: 1, max: 255)
    |> unique_constraint(:name)
  end

  @doc false
  def logo_changeset(group, attrs) do
    group
    |> cast_attachments(attrs, [:logo])
  end
end

lib/ferry_web/controllers/group_controller.ex
defmodule FerryWeb.GroupController do
  use FerryWeb, :controller

  alias Ferry.Links
  alias Ferry.Locations
  alias Ferry.Profiles
  alias Ferry.Shipments

  # Group Controller
  # ==============================================================================

  # Helpers
  # ----------------------------------------------------------

  # TODO: test
  def groups_list_assigns(conn) do
    [
      groups: Profiles.list_groups()
    ]
  end

  # Show
  # ----------------------------------------------------------

  # TODO: add pagination
  def index(conn, _params) do
    render(conn, "index.html", groups: Profiles.list_groups())
  end

  # change (`debug_errors: true` to false in config/dev.exs if you want to
  # test website errors
  def show(conn, %{"id" => id}) do
    group = Profiles.get_group!(id)

    assigns = [
      groups: Profiles.list_groups(),
      group: group,
      links: Links.list_links(group),
      projects: Profiles.list_projects(group),
      addresses: Locations.list_addresses(group),
      shipments: Shipments.list_shipments(group)
    ]

    render(conn, "show.html", assigns)
  end

  # Create
  # ----------------------------------------------------------
  # Create groups using psql directly for now.  See `/README.md` for instructions.

  # Update
  # ----------------------------------------------------------

  def edit(conn, %{"id" => id}) do
    group = Profiles.get_group!(id)

    assigns = [
      groups: Profiles.list_groups(),
      group: group,
      changeset: Profiles.change_group(group),
    ]

    render(conn, "edit.html", assigns)
  end

  def update(conn, %{"id" => id, "group" => group_params}) do
    group = Profiles.get_group!(id)

    case Profiles.update_group(group, group_params) do
      {:ok, group} ->
        conn
        |> put_flash(:info, "Group updated successfully.")
        |> redirect(to: Routes.group_path(conn, :show, group))

      {:error, %Ecto.Changeset{} = changeset} ->
        assigns = [
          groups: Profiles.list_groups(),
          group: group,
          changeset: changeset,
        ]
        render(conn, "edit.html", assigns)
    end
  end

  # Delete
  # ----------------------------------------------------------

  def delete(conn, %{"id" => id}) do
    group = Profiles.get_group!(id)
    {:ok, _group} = Profiles.delete_group(group)

    conn
    |> put_flash(:info, "Group deleted successfully.")
    |> redirect(to: Routes.group_path(conn, :index))
  end

end

lib/ferry_web/views/group_view.ex
defmodule FerryWeb.GroupView do
  use FerryWeb, :view

  def has_groups?(groups) do
    length(groups) > 0
  end

  def has_links?(links) do
    length(links) > 0
  end

  def has_projects?(projects) do
    length(projects) > 0
  end

  def has_shipments?(shipments) do
    length(shipments) > 0
  end


end

lib/ferry_web/templates/group/edit.html.eex
<section class="section section--tabs section--multi">

  <header class="section__header">
    <h1 class="section__title">Groups</h1>

    <nav class="section__nav">
      <ul class="section__tab tab">
        <li class="tab-item">
          <%= link "All Groups", to: Routes.group_path(@conn, :index) %>
        </li>
        <li class="tab-item active">
          <%= link "My Group", to: Routes.group_path(@conn, :show, @current_group.id) %>
        </li>
      </ul>
    </nav>
  </header>

  <div class="section__content">
    <h2 class="col-9 col-ml-auto">Edit Your Group</h2>
    <%= render "form.html", Map.put(assigns, :action, Routes.group_path(@conn, :update, @group)) %>
  </div>

  <div class="section__content">
    <p class="text-small">
      It is currently not possible to delete your group through the app.  We
      certainly respect your privacy and autonomy- if you feel like you aren't
      ready to include your group on the Distribute Aid website please email
      <a href="mailto:help@distributeaid.org">help@distributeaid.org</a> and one
      of our technical team members will assist you.
    </p>

  </div>
</section>

lib/ferry_web/templates/group/form.html.eex
<%= form_for @changeset, @action, [multipart: true, class: "form-horizontal"], fn f -> %>
  <%= component "required.partial.html" %>

  <%= if @changeset.action do %>
    <div class="toast toast-error">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group form-group--required <%= validation_status_class(f, :name) %>">
    <%= label f, :name %>
    <%= text_input f, :name, class: "form-input", placeholder: "Mutual Aid Solidarity Club" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group <%= validation_status_class(f, :logo) %>">
    <%= label f, :logo %>
    <%= file_input f, :logo, class: "form-input" %>
    <%= error_tag f, :logo %>
  </div>

  <div class="form-group <%= validation_status_class(f, :description) %>">
    <%= label f, :description %>
    <%= textarea f, :description, class: "form-input", placeholder: "Tell us about your group..." %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group col-9 col-ml-auto">
    <%= submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

lib/ferry_web/templates/group/index-table.partial.html.eex
<%= if has_groups? @groups do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Controls</th>
        <th>Projects</th>
      </tr>
    </thead>
    <tbody>
  <%= for group <- @groups do %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td>
          <span><%= link "Show", to: Routes.group_path(@conn, :show, group), class: "btn btn-sm" %></span>
          <span><%= link "Edit", to: Routes.group_path(@conn, :edit, group), class: "btn btn-sm" %></span>
          <span><%= link "Delete", to: Routes.group_path(@conn, :delete, group), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-sm" %></span>
        </td>
        <td>
          <%= link "Projects", to: Routes.group_project_path(@conn, :index, group) %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>

<% else %>
  <p>
    No groups have been created.
  </p>
<% end %>

lib/ferry_web/templates/group/index.html.eex
<section class="section section--tabs">

  <header class="section__header">
    <h1 class="section__title">Groups</h1>

    <nav class="section__nav">
      <ul class="section__tab tab">
        <li class="tab-item active">
          <%= link "All Groups", to: Routes.group_path(@conn, :index) %>
        </li>
        <%= if @current_group != nil do %>
          <li class="tab-item">
            <%= link "My Group", to: Routes.group_path(@conn, :show, @current_group.id) %>
          </li>
          <!-- TODO: else sign up prompt? -->
        <% end %>
      </ul>
    </nav>
    <%= if is_nil(@current_group) do %>
      <%= link to: Routes.user_path(@conn, :new), class: "btn btn-primary tooltip tooltip-left section__action", data: [tooltip: "Sign up for an account to add your group's profile!"] do %>
        <i class="fas fa-lg fa-plus-circle is-icon-left"></i> Add Your Group
      <% end %>
    <% end %>
  </header>

  <div class="section__content">
    <table id="group-index" class="table table-striped">

      <thead>
        <tr>
          <th><!-- Actions --></th>
          <th> Group </th>
        </tr>
      </thead>

      <tbody>
        <%= if has_groups? @groups do %>
          <%= for group <- @groups do %>
            <tr>
              <td>
                <%= component "action.partial.html", %{
                  action: :view,
                  authorized?: true,
                  route: Routes.group_path(@conn, :show, group)
                } %>
              </td>
              <td>
                <%= link to: Routes.group_path(@conn, :show, group), class: "link--unstyled" do %>
                  <%= component "group_logo.partial.html", %{
                    conn: @conn,
                    group: group,
                    size: :lg,
                    fill: true
                  } %>
                  <div class="group-details">
                    <%= group.name %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>

        <% else %>
          <p>
            No groups have been created... yet!
          </p>
        <% end %>
      </tbody>

    </table>
  </div>

</section>

lib/ferry_web/templates/group/show.html.eex
<section class="section section--tabs section--multi">

  <header class="section__header">
    <h1 class="section__title">Groups</h1>

    <nav class="section__nav">
      <ul class="section__tab tab">
        <%= if @current_group != nil && @current_group.id == @group.id do %>
          <li class="tab-item">
            <%= link "All Groups", to: Routes.group_path(@conn, :index) %>
          </li>
        <% else %>
          <li class="tab-item active">
            <%= link "All Groups", to: Routes.group_path(@conn, :index) %>
          </li>
        <% end %>

        <%= if @current_group != nil do %>
          <%= if @current_group.id == @group.id do %>
            <li class="tab-item active">
              <%= link "My Group", to: Routes.group_path(@conn, :show, @current_group.id) %>
            </li>
          <% else %>
            <li class="tab-item">
              <%= link "My Group", to: Routes.group_path(@conn, :show, @current_group.id) %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </nav>
    <%= if is_nil(@current_group) do %>
      <%= link to: Routes.user_path(@conn, :new), class: "btn btn-primary tooltip tooltip-left section__action", data: [tooltip: "Sign up for an account to add your group's profile!"] do %>
        <i class="fas fa-lg fa-plus-circle is-icon-left"></i> Add Your Group
      <% end %>
    <% end %>
  </header>

  <div class="section__content">
    <div class="content-header content-header--no-underline">
      <%= component "group_logo.partial.html", %{
        conn: @conn,
        group: @group,
        size: :xxl
      } %>

      <h2 class="content-header__title"><%= @group.name %></h2>

      <%= component "action.partial.html", %{
        action: :edit,
        authorized?: !is_nil(@current_group) && @group.id == @current_group.id,
        route: Routes.group_path(@conn, :edit, @current_group)
      } %>
    </div>

    <%= if @group.description do %>
      <p>
        <%= @group.description %>
      </p>
    <% end %>
  </div>

  <%= if length(@links) > 0 ||  (!is_nil(@current_group) && @group.id == @current_group.id) do %>
    <div class="section__content">
      <%= render FerryWeb.LinkView, "index-list.partial.html", %{
        conn: @conn,
        group: @group,
        links: @links,
        can_modify?: !is_nil(@current_group) && @group.id == @current_group.id
      } %>
    </div>
  <% end %>

  <%= if length(@projects) > 0 ||(!is_nil(@current_group) && @group.id == @current_group.id) do %>
    <div class="section__content">
        <%= render FerryWeb.ProjectView, "index-list.partial.html", %{
          conn: @conn,
          group: @group,
          projects: @projects,
          can_modify?: !is_nil(@current_group) && @group.id == @current_group.id
        } %>
    </div>
  <% end %>

  <%= if length(@addresses) > 0 || (!is_nil(@current_group) && @group.id == @current_group.id) do %>
    <div class="section__content">
      <%= render FerryWeb.AddressView, "index-list.partial.html", %{
        conn: @conn,
        group: @group,
        addresses: @addresses,
        can_modify?: !is_nil(@current_group) && @group.id == @current_group.id
      } %>
    </div>
  <% end %>

  <%= if length(@shipments) > 0 || (!is_nil(@current_group) && @group.id == @current_group.id) do %>
    <div class="section__content">
      <%= render FerryWeb.ShipmentView, "index-list.partial.html", %{
        conn: @conn,
        group: @group,
        shipments: @shipments,
        can_modify?: !is_nil(@current_group) && @group.id == @current_group.id
      } %>
    </div>
  <% end %>

</section>